# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: Liz Muehlmann
email: liz.muehlmann@uci.edu
description: Academic website for Liz Muehlmann, Political Science PhD Candidate at the University of California Irvine
#baseurl: "" # the subpath of your site, e.g. /blog
url: https://liz-muehlmann.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hello_iamliz
github_username:  liz-muehlmann
search_full_content: false
repository: "liz-muehlmann/liz-muehlmann.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh

# [for] Notes:
excerpt_separator: <!-- more -->

markdown: kramdown
highlighter: rouge
# kramdown:
#   input: GFM
#   syntax_highlighter_opts:
#     default_lang: r
#     css_class: 'highlight'
#     span:
#       line_numbers: false
#     block:
#       line_numbers: true
#       start_line: 1