title: Liz Muehlmann
email: 'lizmuehlmann@gmail.com'
description: Liz Muehlmann | PhD Candidate in Political Science at the University of Irvine, California.
baseurl: /
url: https://liz-muehlmann.github.io
bluesky_username: '@hello_iamliz'
github_username: liz-muehlmann
author: Liz