title: Liz Muehlmann
email: 'liz.muehlmann@uci.edu'
description: Academic website for Liz Muehlmann. PhD Candidate in Political Science at the University of Irvine, California.
baseurl: /
url: https://liz-muehlmann.github.io
twitter_username: '@hello_iamliz'
github_username: liz-muehlmann
author: Liz